In [1]:
import numpy as np

# Generate a random 5x5 matrix
matrix = np.random.randint(1, 100, size=(5, 5))

print("Random Matrix:")
print(matrix)

# Find minimum and maximum values along each row
min_row_values = np.min(matrix, axis=1)
max_row_values = np.max(matrix, axis=1)

print("\nMinimum values along each row:")
print(min_row_values)
print("\nMaximum values along each row:")
print(max_row_values)

# Find minimum and maximum values along each column
min_col_values = np.min(matrix, axis=0)
max_col_values = np.max(matrix, axis=0)

print("\nMinimum values along each column:")
print(min_col_values)
print("\nMaximum values along each column:")
print(max_col_values)

Random Matrix:
[[90 92 89  7  4]
 [64 65 16  9 41]
 [96 52 15 79 24]
 [18 17 56 57 16]
 [57 69 23 59 87]]

Minimum values along each row:
[ 4  9 15 16 23]

Maximum values along each row:
[92 65 96 57 87]

Minimum values along each column:
[18 17 15  7  4]

Maximum values along each column:
[96 92 89 79 87]
